deploy:
  provider: puppetforge
  user: jamesmcdonald
  password:
    secure: aLrdoQ683L7zr59cFcBb3hrEJ3xTjXtXqoT6u0VhNAk+SOT7qqKqX0Nbk10koXLX7qF4/pwMOMa4PxP7tsjk+EUKTaq8HmuzB/yN1kP+WgWVetr1DnagaLVTyU8y8C55Qe21/wq0GgweNjZcMiMT15xxIQxXYcJ79jE114Grha0/IhDCfpmX+XsvCa/Uk6EF5sDKHceienDZVWQ6chAU/Qu6v4PRFrj4EQt5ijT0avBNLJjIORM6324JI5ywD2rEwDzaBI+4znfnXFPQlyCeKX3jCnlpmHG9tWHhj3/SDoBZzI7PB282h12+gIaTrIE4xnqC6nbYgjQHovMbZyjJRYumlUg/XlGyB6cLaprUySwDv60Q/Dte8TvnJcSKAkMs5ofZQuEzKke0cgLHDeeahrTX8j3rTwDyLm91lsidWvsoGFDyNL1/GAHzRPI33hzuoZ8P07iZDsYDOyuA8j1nFd6E6eU188Y9Mci84RgermZs65iq1VbzHMky45wcHMnRh4/2mB4uCGgk2ZZ3HQUpN7gHnluWdifnN8/6JCke/QUC/Gugerml4eY4GvHMRwE/Q2L95Wc9WVpk8iX3VOqyB3gHqTVrP43larm/LLwUTwHRTcmYwnXDXf7qQmpOB6tvW5fqMZh1vlqe2iR2+nP6wEmkgj5xLoB6EHdNVPH6uJE=
  on:
    tags: true
    all_branches: true
